package com.intelisale.networking.schema.sync;

public interface SyncTableNames {

    String BackOrderShipmentStatuses = "BackOrderShipmentStatuses";                 // +    CodeBook
    String CategoriesOfItems = "CategoriesOfItems";                                 // +    CodeBook
    String Contacts = "Contacts";                                                   // +
    String ContactsDepartments = "ContactsDepartments";                             // +    CodeBook
    String ContactsPositions = "ContactsPositions";                                 // +    CodeBook
    String Customers = "Customers";                                                 // +
    String CustomersEmployees = "CustomersEmployees";                               //
    String CustomersUsers = "CustomersUsers";                                       // +    With Customers
    String CustomerShipToAddresses = "CustShipToAddresses";                         // +    With Customers
    String CustomerPaymentMethods = "CustPaymentMethods";                           // +    CodeBook
    String CustomerPaymentConditions = "CustPaymentConditions";                     // +    CodeBook
    String CustomerShipmentMethods = "CustShipmentMethods";                         // +    CodeBook
    String CustomerStatistics = "CustomerStatistics";                               // +    With Customers
    String CustomerVisits = "CustomerVisits";                                       // +    With Customers
    String CustomerPlanTurnover = "CustomerPlanTurnover";                           // +    With Customers
    String CustomerProductGroupPotential = "CustomerProductGroupPotential";         // +    With Customers
    String DocumentTypes = "DocumentTypes";                                         // +    CodeBook
    String GroupsOfCustomers = "GroupsOfCustomers";                                 // +    CodeBook and Through Customer
    String Items = "Items";                                                         // +
    String ItemUnitOfMeasures = "ItemUnitOfMeasures";                               // +    CodeBook
    String PostalCodesAndCities = "PostalCodesAndCities";                           // +    CodeBook
    String Municipalities = "Municipalities";                                       // +    CodeBook
    String SalesDocumentConditions = "SalesDocumentConditions";                     // +    CodeBook
    String SalesDocumentTypes = "SalesDocumentTypes";                               // +    CodeBook
    String SalesPriceTypes = "SalesPriceTypes";                                     // +    CodeBook
    String SalesTypes = "SalesTypes";                                               // +    CodeBook
    String Settings = "Settings";                                                   //      CodeBook
    String VATItemCustomerGroupsSetups = "VATItemCustGroupsSetups";                 //
    String VisitResults = "VisitResults";                                           // +    CodeBook
    String Warehouses = "Warehouses";                                               // +    CodeBook
    String SLItemsCustomersCards = "SLItemsCustomersCards";                         // +
    String SLItemsPerProcessesPerCustomers = "SLItemsPerProcessesPerCustomers";     // +
    String SLItemsAllowedToCustomers = "SLItemsAllowedToCustomers";                 // +    With Items and SalesLeader
    String SLProcessesPerCustomers = "SLProcessesPerCustomers";                     // +    CodeBook With Customers
    String SLItemsConnections = "SLItemsConnections";                               // +    CodeBook With Items
    String SLItemsPackages = "SLItemsPackages";                                     // +    CodeBook With Items
    String SLDirections = "SLDirections";                                           // +    CodeBook
    String SLSalesLevelTypes = "SLSalesLevelTypes";                                 // +    CodeBook
    String SLShelvesPerCustomers = "SLShelvesPerCustomers";                         // +    CodeBook With Customers
    String SLItemsPerShelvesPerCustomers = "SLItemsPerShelvesPerCustomers";         // +
    String SLCustomerCardColors = "SLCustomerCardColors";                           // +    CodeBook
    String DocumentVerificationStatuses = "DocumentVerificationStatuses";           // +    CodeBook
    String Tags = "Tags";                                                           // +    CodeBook
    String SLCategoriesAllowedToCustomer = "SLCategoriesAllowedToCustomer";         // +    With Customers
    String SLNewItemsCustomersCard = "SLNewItemsCustomersCard";                     // +    With SalesLeader on request
    String SLNewItemsCustomersCardCount = "SLNewItemsCustomersCardCount";           // +    With SalesLeader
    String Comments = "Comments";                                                   // +    With Customers
    String CommentsSources = "CommentsSources";                                     // +    CodeBook
    String CommentsTargets = "CommentsTargets";                                     // +    CodeBook
    String ItemStatuses = "ItemStatuses";                                           // +    CodeBook
    String CustomLists = "CustomLists";                                             // +    CodeBook
    String TablesDeletedInserted = "TablesDeletedInserted";                         // +
    String CreatedDocumentStatuses = "CreatedDocumentStatuses";                     // +    CodeBook
    String TransactionTypes = "TransactionTypes";                                   // +    CodeBook
    String ServiceOrdersStatuses = "ServiceOrdersStatuses";                         // +    CodeBook
    String Notes = "Notes";                                                         // +
    String NotesTargetTypes = "NotesTargetTypes";                                   // +    CodeBook
    String NotesTargetGroups = "NotesTargetGroups";                                 // +    CodeBook
    String NotesAttachments = "NotesAttachments";                                   // +
    String Users = "Users";                                                         // +
    String ApprovalStatuses = "ApprovalStatuses";                                   // +    CodeBook
    String SLItemsCustomersCardsICO = "SLItemsCustomersCardsICO";                   // +
    String ServiceClassification = "ServiceClassification";                         // +    CodeBook
    String ServiceClassificationTypes = "ServiceClassificationTypes";               // +    CodeBook
    String StockAvailabilityStatus = "StockAvailbilityStatus";                      // +    CodeBook
    String SLItemSoldToCustomerMonthly = "SlitemSoldToCustomerMonthly";             // +
    String GroupOfCustomersCategoryItems = "GroupOfCustomersCategoryItems";         // +
    String CustomersCustomLists = "CustomersCustomLists";                           // +    With Customers
    String CustomListsHeaders = "CustomListsHeaders";                               // +
    String CustomListsLines = "CustomListsLines";                                   // +    With Customers
    String VisitsFrequencies = "VisitsFrequencies";                                 // +    With Customers
}